### ISSUE TITLE
Enable RUM integration

### ISSUE THREAD

**Issue by felixbarny** [elastic/opbeans-java#21]
Use the new API methods to enable RUM correlation: https://www.elastic.co/guide/en/apm/agent/java/master/public-api.html#api-ensure-parent-id

The difficulty is that Opbeans should probably still work with older versions. So the version of the API has to be fixed to 1.0.0.RC1 or 1.0.0, when it's released. The API is backwards compatible so it is possible to use older agents with the new API.

**Comment by roncohen** [comment]
could you add a new endpoint that would serve from HTML (for example the same `index.html`) but also create some spans before responding? This wouldn't be a great example initially, but would get us started

**Comment by roncohen** [comment]
would be great to have this as a way to demonstrate that RUM integration actually works.

**Comment by jackshirazi** [comment]
Is this still desired?
